language: node_js
node_js: stable

cache:
  yarn: true
  directories: node_modules

script: yarn test

after_success: yarn run coverage

notifications:
  email:
    on_success: change
    on_failure: change
